### ISSUE TITLE
"iphone" shortname code for mobile phone

### ISSUE THREAD

**Issue by tomkiss** [joypixels/emoji-toolkit#11]
Hi there,

The Unicode emoji for 'MOBILE PHONE' (U+1F4F1) has a shortname of "iPhone" in the EmojiOne / JoyPixels library.

Is there any reason for this renaming? It presents a bias towards Apple, as there is no Android or competitor counterpart. Additionally, this presents a problem for license holders integrating emojis in to competing platforms to Apple.

Might it be better to apply iPhone as a shortname, using a name like mobilephone which is closer to the Unicode source name?

**Comment by caseyahenson** [comment]
Hi, thanks for pointing this out! Yes we will have this renamed with our 5.5 release scheduled for this month.

**Comment by caseyahenson** [comment]
Resolved in release 5.5.0.
