### ISSUE TITLE
Picker compatibility?

### ISSUE THREAD

**Issue by alexthekid07** [joypixels/emoji-toolkit#12]
Is there any workaround to using 4.x or 5.x with mervick/emojionearea or any "pickers"?

Since the rename to "joypixels" and updates, any of the picker's I've looked at using are incompatible.

**Comment by caseyahenson** [comment]
I'm not aware of any off hand, however I'll ask around and keep and eye out to see what I can find. If you come across anything please do post it here as well. Thanks!
