### ISSUE TITLE
shortnameToUnicode() returns code instead of emoji

### ISSUE THREAD

**Issue by jf-ouellette** [joypixels/emoji-toolkit#13]
Hi!

We recently upgraded your PHP package from 2.2.7 to 5.0.5 and it looks like we are getting a different return from the shortnameToUnicode() function. We used to get a string containing emojis from that function, but now we end up with a string containing codes. Here is our code:

`use JoyPixels\Client as EmojiClient;`
`use JoyPixels\Ruleset as EmojiRuleset;`

`// ...`

`$emoji = new EmojiClient(new EmojiRuleset());`

`$body = $emoji->toShort($rawBody);`
`$encodedBody = $emoji->shortnameToUnicode($body);`

Let's say $rawBody value is `:grinning:`
- In 2.2.7, $encodedBody value would be `😃`
- In 5.0.5, $encodedBody value is `&#x1f600;`

I looked at the documentation, the issues and the upgrade guide, but I didn't find anything explaining why this is happening.

Am I missing something?
Thank you!

**Comment by caseyahenson** [comment]
Resolved in release 5.5.0.
