### ISSUE TITLE
How to set as default emoji font?

### ISSUE THREAD

**Issue by gsbhasin123** [joypixels/emoji-toolkit#15]
I want it to be the default emoji font for Brave/Chromium and Firefox as well as everything else on my system - how can I do this?

**Comment by caseyahenson** [comment]
@gsbhasin123 depending upon your system, you can install one of our fonts from here: [JoyPixels Downloads](https://www.joypixels.com/download). Let me know if you have any issues.

**Comment by gsbhasin123** [comment]
Is there a linux version?

**Comment by caseyahenson** [comment]
@gsbhasin123 so sorry for the delayed response. You may want to try the android TTF file provided in the fonts download: https://www.joypixels.com/download. This is currently deployed as an arch-linux package found here: https://www.archlinux.org/packages/community/any/ttf-joypixels/. Hopefully this will work for your installation as well.

**Comment by gsbhasin123** [comment]
Awesome! :D I use Arch, I'll try that
