### ISSUE TITLE
Ruleset.php is outdated for 5.5.0

### ISSUE THREAD

**Issue by mikhailter** [joypixels/emoji-toolkit#19]
Hi, Ruleset.php is outdated for 5.5.0 release. Is there any way to regenerate it?

https://github.com/joypixels/emoji-toolkit/blob/master/lib/php/src/Ruleset.php

**Comment by caseyahenson** [comment]
Hi @mikhailter thank you for pointing this out. I'll review and post any updates shortly.

**Comment by caseyahenson** [comment]
This is fixed in 5.5.1, just released. Let me know if you're still experiencing any issues.
