### ISSUE TITLE
Heart shortnameToUnicode is outputting wrong UTF-8

### ISSUE THREAD

**Issue by Andy6792** [joypixels/emoji-toolkit#2]
We recently upgraded from emojiOne v4.5 to JoyPixels v5.

We are using the joypixels.js file, and noticed that since upgrading the shortnameToUnicode is outputting the wrong UTF-8 for the heavy black heart emoji. 

```
var input = ':heart:';
var emoji = joypixels.shortnameToUnicode(input);
```

The old 4.5 JS library used to output this UTF-8 hex...

**e29da4**

Now it outputs this...

**e29da4efb88f**

It appears the UTF-8 hex is wrong, according to...

https://www.fileformat.info/info/unicode/char/2764/index.htm

**Comment by caseyahenson** [comment]
@Andy6792 we're always working for a more accurate dataset, and part of that for 5.0 included a review of our usage of variation selectors. We're now adhering to this list: https://www.unicode.org/Public/emoji/12.0/emoji-variation-sequences.txt as far as matching and outputting is concerned. In the case of red heart, we were noticing that systems did not always render the UTF-8 hex code of `e29da4` (without variation selector) as an emoji and instead in text format.

Were you running into any issues with this output for 5.0?

**Comment by Andy6792** [comment]
@caseyahenson - No worries. No issues, we were just questioning why things changed. But this makes perfect sense. Now we know we have amended our product to work with the new heart code. Thanks 👍
