### ISSUE TITLE
Could you also update emoji_strategy.json ?

### ISSUE THREAD

**Issue by frbodya** [joypixels/emoji-toolkit#20]
because in emoji.json some "fully_qualified" isn't correct, but in emoji_strategy correct.

For example: "Hand with Fingers Splayed" it has unicode U+1F590 U+FE0F, in emoji_strategy.json it correct unicode "1f590-fe0f", but in emoji.json just "1f590"

**Comment by caseyahenson** [comment]
@frbodya thank you for bringing this to our attention. I'll review and post any updates shortly.

**Comment by caseyahenson** [comment]
This is fixed in 5.5.1. The correct code point for hand with fingers splayed should not include the vs16 indicator, FE0F, so the emoji.json file was correct. Let me know if you're experiencing any issues with this.
