### ISSUE TITLE
Access Denied issue with emojione svg

### ISSUE THREAD

**Issue by tiggem1993** [joypixels/emoji-toolkit#21]
Following emojione urls are Access Denied:
1. https://cdn.jsdelivr.net/emojione/assets/svg/1f9fc.svg
2. https://cdn.jsdelivr.net/emojione/assets/svg/1f9fd.svg

**Comment by caseyahenson** [comment]
@tiggem1993 Beginning with our v3.0 release, we no longer distribute SVGs via CDN. Nowadays the route you're looking for includes some additional parameters including the emoji version and naming convention, for example: https://cdn.jsdelivr.net/joypixels/assets/5.5/png/unicode/128/1f9fc.png. Hopefully this helps!
