### ISSUE TITLE
Version 6

### ISSUE THREAD

**Issue by chrisdeeming** [joypixels/emoji-toolkit#28]
Please do forgive my ignorance here, I'm not trying to have a dig or anything this is just a genuine question. I have observed that after a major JoyPixels update that the licenses go for sale and the joypixels/emoji-assets get updated almost straight away, but this repository tends to lag behind.

What is usually the reason for this and when might you envisage the toolkit being updated for version 6.

Many thanks!

**Comment by basmilius** [comment]
I'm also wondering why this is lacking behind, I have a 6.0 license but cannot use the new emoji's in my project because this repository isn't updated yet.

**Comment by caseyahenson** [comment]
This is now fixed, apologies for the late update!
