### ISSUE TITLE
Release 6 emoji.json does not contain any Unicode 13 emojis

### ISSUE THREAD

**Issue by holgerde** [joypixels/emoji-toolkit#31]
The emoji.json file released with version 6.0.0 does not contain any entries for Unicode 13 emojis. It also contains some obsolete short names, such as bride_with_veil, which is now called person_with_veil, so it cannot be converted using shortnameToImage().

The emoji.json in the master branch seems to be correct, but is different from the version released with 6.0.0.

**Comment by caseyahenson** [comment]
This is fixed in the 6.0.1 patch release just now.
