### ISSUE TITLE
Shortnames doesn't works to :+1:

### ISSUE THREAD

**Issue by djorkaeffalexandre** [joypixels/emoji-toolkit#4]
I use JS lib and when i send `:+1:` to `shortnameToUnicode()` it not works..
I debugged it and not found `:+1:` on `ns.shortnames`... :(

Some emojis like `:man_facepalming_light_skin_tone:` doesn't work too with this method, I changed [this line](https://github.com/joypixels/emoji-toolkit/blob/master/lib/js/joypixels.js#L248) to:
`if( (typeof shortname === 'undefined') || (shortname === '') || (ns.shortnames.indexOf(shortname) === -1) ) {`
and it works fine with `:man_facepalming_light_skin_tone:`..

**Comment by djorkaeffalexandre** [comment]
I'm using `v5.0.4`.

**Comment by caseyahenson** [comment]
@djorkaeffalexandre 5.0.5 was just released to address the issue with `:+1:` not replacing properly. However, I cannot recreate your issue with `:man_facepalming_light_skin_tone:`. Does this work for you on the [shortnameToImage() demo](https://demos.joypixels.com/latest/jsshortnametoimage.html)?
