### ISSUE TITLE
`<3` emoticon doesn't work

### ISSUE THREAD

**Issue by adrianhuna** [joypixels/emoji-toolkit#7]
If you have `ascii` support enabled, then the `<3` breaks conversion (at least for the JS library).

You can try it out on your demo page:
https://demos.joypixels.com/latest/ascii-smileys.html

![image](https://user-images.githubusercontent.com/8538900/66243109-a0311480-e703-11e9-90d6-898b7a910253.png)

**Comment by zarko-tg** [comment]
Any hope for this? Turns out people like using heart ascii (<3).

**Comment by gsbhasin123** [comment]
<3

**Comment by caseyahenson** [comment]
Resolved in release 5.5.0.
