### ISSUE TITLE
Emoji Picker Component

### ISSUE THREAD

**Issue by fabriciofrontarolli** [joypixels/emoji-toolkit#9]
I need to build an emoji picker. is there any json containing a complete list of emojis so I can display to the user in a emoji picker?

**Comment by caseyahenson** [comment]
@fabriciofrontarolli see the emoji.json file included in this repository: https://github.com/joypixels/emoji-toolkit/blob/master/emoji.json. This contains each emoji available with information including title, category, and in some cases keywords.
